name: Minetrends
version: '${project.version}'
website: www.Minetrends.com
author: NXTGUY & VolcanicPlaza

main: com.volcanicplaza.Minetrends.Minetrends
database: false

commands:
  minetrends:
    descrption: Main command for the MineTrends plugin.
    aliases: [minet, mtrends]
